#!/bin/sh
name="rk817-battery"
path="/sys/class/power_supply/$name"

read full < "$path/charge_full_design"

while true;
do
	read charge < "$path/charge_now"
	read status < "$path/status"

	if [ $(($charge * 100 / $full)) -lt 10 ] && [ "$status" = "Discharging" ]; then
		tmux display-message "Battery low"
	fi

	sleep 30;
done
